### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Nikhil2919** [nicolasmiller/pyculiarity#13]
I am trying to run the detect_ts function from pyculiarity package but getting this error on passing a two-dimensional dataframe.
>>> data=pd.read_csv('C:\\Users\\nikhil.chauhan\\Desktop\\Bosch_Frame\\dataset1.csv',usecols=['A','B'])
>>> from pyculiarity import detect_ts
>>> results = detect_ts(data,max_anoms=0.02,alpha=0.001,direction = 'both',only_last=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: detect_ts() got an unexpected keyword argument 'only_last'
>>> results = detect_ts(data,max_anoms=0.02,alpha=0.001,direction = 'both')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nikhil.chauhan\Downloads\Compressed\pyculiar-0.0.5\pyculiarity\detect_ts.py", line 177, in detect_ts
    verbose=verbose)
  File "C:\Users\nikhil.chauhan\Downloads\Compressed\pyculiar-0.0.5\pyculiarity\detect_anoms.py", line 69, in detect_anoms
    decomp = stl(data.value, np=num_obs_per_period)
  File "C:\Users\nikhil.chauhan\Downloads\Compressed\pyculiar-0.0.5\pyculiarity\stl.py", line 35, in stl
    res = sm.tsa.seasonal_decompose(data.values, model='additive', freq=np)
  File "C:\Anaconda3\lib\site-packages\statsmodels\tsa\seasonal.py", line 88, in seasonal_decompose
    trend = convolution_filter(x, filt)
  File "C:\Anaconda3\lib\site-packages\statsmodels\tsa\filters\filtertools.py", line 303, in convolution_filter
    result = _pad_nans(result, trim_head, trim_tail)
  File "C:\Anaconda3\lib\site-packages\statsmodels\tsa\filters\filtertools.py", line 28, in _pad_nans
    return np.r_[[np.nan] * head, x, [np.nan] * tail]
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by HozcarAndres** [comment]
Are you working with windows? please read https://gehrcke.de/2015/02/how-to-set-up-a-64-bit-version-of-numpy-on-windows/
