### ISSUE TITLE
No module named 'detect_vec'

### ISSUE THREAD

**Issue by rangeles-localytics** [nicolasmiller/pyculiarity#3]
Hi, forgive my naivety but I'm getting an import error after I installed the module and imported it into a test project file. It seems to originate from the init file.

**Comment by codeb2cc** [comment]
Are you using Python 3? This module is not compatible with Python 3 yet. But there's a quick fix:

```
cd PYTHONHOME/site-packages
2to3 -w -n pyculiarity
```

**Comment by jagannath79** [comment]
Can you explain how to run this

**Comment by michael-erasmus** [comment]
@codeb2cc I just sent a PR that will let automatically run `2to3` on a `pip install` on Python 3.

I tested it out on my own fork locally and everything seems to work great

https://github.com/nicolasmiller/pyculiarity/pull/8

**Comment by codeb2cc** [comment]
@michael-erasmus Since I don't have the write access of this repository I can't merge the PR.
You should @nicolasmiller

**Comment by michael-erasmus** [comment]
@codeb2cc ah, sorry about that, didn't notice I was pinging the wrong person :D

**Comment by michael-erasmus** [comment]
My PR has been merged, so this issue should be resolved now

**Comment by Archit2510** [comment]
I am facing the same issue, Can anyone help me with this?

**Comment by hubertrogers** [comment]
Also having this issue.

**Comment by shivonkar** [comment]
I Installed fresh on python 3.6 and getting same issue "No module named 'detect_vec'"

Any workaround or help

**Comment by Srivathsan-Srinivas** [comment]
same here. Any help would be appreciated.

```
Traceback (most recent call last):
  File "main_prg.py", line 13, in <module>
    from AnomalyDetection import AnomalyDetection
  File "/Users/sri/src/AnomalyDetection.py", line 9, in <module>
    from pyculiarity import detect_ts
  File "/Users/sri/p3venv/lib/python3.6/site-packages/pyculiarity/__init__.py", line 12, in <module>
    from detect_vec import detect_vec
ModuleNotFoundError: No module named 'detect_vec'
```
